language: node_js
node_js: "8"
cache: yarn
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
script:
- "npm test"
- "npm run lint"
before_deploy:
- "npm run build"
